server:
 port: 8080
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka
spring:
 application:
  name: gateway-service
cloud:
 loadbalancer:
  enabled: true
gateway:
 routes:
  id: gallery-service
  uri: http://localhost:8100/
  predicates:
   Path=/gallery/**